language: ruby
rvm:
- 2.3.0
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --check-opengraph
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: G3jUFG5XIJIkFJ4ZvLgqdNb/x2+GEuN7bsPy1JcWJOXJpsF7a7Ykc5hcIHbK5Zqp9/4eV5j+k6hiljB5e9NlYxxDXbIJOFIzFD9N66RRgkzLsYJKpSLPfHFV4PtmNQSWPvuIMX3BvD9RwEdEdyidwcpR4g6hAiIpTmLb1+SoVn6cgJkftkTL3BHvtUXvkQOLSBTVny0pXui7vjt+YL33eWecV/S8+7UPSOJ8MYswIbPlDjPLwK31O0Dt8DIj4XxgYvrlyqEA4/GG58Sc1XXoIpHS1MknN9q8uio89LNlQxmogyuns0Q/KAfG5nLoEMFHdJCbR0jay6fWHKtIemyoSxDSBL+JhMm5vayTvxZLZNgd4u3DQ+bx7WJpBmYGwt89xZgX1wrNXzJqQnfb7Iqw42bHp9QYQF9QzrcnjLGkA9B1szv1gqodbyO6eTflxG1hMS7f29d89446jl7devWRaG1QvOVZKWyYrbEUVTs+Gh7FzgHKQIlXRdY0Csk5knvT7SZgMvFnRTZWTX93KgIoNE7TuL1Wexh2vwbGLeigSibCKAv2ZBSGUSi0CAxJTRP+J+EyPUM+pdsFmDUkqps1SgSEOkRNtHJxlgprM05/HJoEYYon8A+BoLqbAIBw6G9hY8Klx8rXPRvlny3e6X/tJANbRA0h2lLf68g85HVHwoQ=
notifications:
  email:
    recipients:
      - paul@baggerspion.net
    on_success: always
    on_failure: always